### ISSUE TITLE
Multiparameter type classes / MTL

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#9] opened 2017-11-30 11:12 UTC
```haskell
data W s trans m a = W (trans m a)

instance Functor     (W s trans m) 
instance Applicative (W s trans m) 
instance Monad       (W s trans m)

instance (MonadTrans trans, MonadState s m) => MonadState s (W s trans m) where
  get :: W s trans m s
  get = W (lift get)

  put :: s -> W s trans m ()
  put = W . lift . put

  state :: (s -> (a, s)) -> W s trans m a
  state = W . lift . state
```

Trying to define this for the `IdentityT` transformer

```haskell
newtype IDENTITYT m a = IDENTITYT (m a)
  deriving (MonadState s)
    via (W s IDENTITYT m)

instance MonadTrans IDENTITYT where
  lift :: m a -> IDENTITY m a
  lift = IDENTITYT
```

This produces

```
ghc-stage2: panic! (the 'impossible' happened)
  (GHC version 8.3.20171122 for x86_64-unknown-linux):
	ASSERT failed!
  in_scope InScope {m_aoCp s_aoCs}
  tenv [anWw :-> s_aoCs, anWx :-> W s_aoCr IDENTITYT m_aoCp]
  tenvFVs [aoCp :-> m_aoCp, aoCr :-> s_aoCr, aoCs :-> s_aoCs,
           aoGg :-> k_aoGg, aoGY :-> k_aoGY]
  cenv []
  cenvFVs []
  tys [m_anWx s_anWw]
  cos []
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1205:22 in ghc:Outputable
        assertPprPanic, called at compiler/types/TyCoRep.hs:2126:56 in ghc:TyCoRep
        checkValidSubst, called at compiler/types/TyCoRep.hs:2159:29 in ghc:TyCoRep
        substTy, called at compiler/typecheck/TcGenDeriv.hs:1727:11 in ghc:TcGenDeriv
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1147:37 in ghc:Outputable
        pprPanic, called at compiler/utils/Outputable.hs:1203:5 in ghc:Outputable
        assertPprPanic, called at compiler/types/TyCoRep.hs:2126:56 in ghc:TyCoRep
        checkValidSubst, called at compiler/types/TyCoRep.hs:2159:29 in ghc:TyCoRep
        substTy, called at compiler/typecheck/TcGenDeriv.hs:1727:11 in ghc:TcGenDeriv

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

> 
```

**Comment by RyanGlScott** [comment] 2017-11-30 14:26
Closing as a duplicate of #7.

**Closed as completed by RyanGlScott** 2017-11-30 14:26 UTC
