### ISSUE TITLE
GHC panics on (newtype I = I [Int] deriving Show via [a])

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#21] opened 2018-01-17 21:38 UTC
Creating ticket in case this is new

```haskell
$ ghci -ignore-dot-ghci
GHCi, version 8.5.20180105: http://www.haskell.org/ghc/  :? for help
>>> :set -XDerivingVia 
>>> newtype I = I [Int] deriving Show via [a]

<interactive>:2:30: error:ghc-stage2: panic! (the 'impossible' happened)
  (GHC version 8.5.20180105 for x86_64-unknown-linux):
	No skolem info:
  [a_a1uz]
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
        pprPanic, called at compiler/typecheck/TcErrors.hs:2901:5 in ghc:TcErrors

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

>> 
```

**Comment by RyanGlScott** [comment] 2018-01-17 21:52
Duplicate of https://github.com/RyanGlScott/ghc/issues/3.

**Closed as completed by RyanGlScott** 2018-01-17 21:52 UTC
