### ISSUE TITLE
Deriving directly via parameter

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#30] opened 2018-04-10 10:22 UTC
This should work ([reddit](https://www.reddit.com/r/haskell/comments/8aa81q/deriving_via_or_how_to_turn_handwritten_instances/dwyxte9/))

```haskell
newtype IntAs eq = I Int

deriving via eq
  instance (Eq eq, Coercible Int eq) => Eq (IntAs eq)
```

I can't get it to work without constraining `(eq::Type)`, even if I make everything else monokinded. This should work too:

```haskell
newtype IntAs eq = I Int
  deriving (Eq)
    via eq
```

**Comment by RyanGlScott** [comment] 2018-04-10 10:26
Can you post the full code you're using, including language extensions? As it stands, you've given me an incomplete program, and I am forced to guess what your true intentions are.

This appears to work:

```haskell
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE StandaloneDeriving #-}
module Foo where

import Data.Coerce

newtype IntAs eq = I Int

deriving via eq
  instance (Eq eq, Coercible Int eq) => Eq (IntAs eq)
```

**Comment by kosmikus** [comment] 2018-04-10 12:14
It stops working once you enable `PolyKinds`. But it's sufficient to then annotate the via-type. So I think this is matching previous discussions and also #29.

**Comment by RyanGlScott** [comment] 2018-04-10 12:16
Ah, right. So this is the program that @Icelandjack is _really_ running:

```haskell
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE StandaloneDeriving #-}
module Foo where

import Data.Coerce

newtype IntAs eq = I Int

deriving via eq
  instance (Eq eq, Coercible Int eq) => Eq (IntAs eq)
```
```
GHCi, version 8.5.20180406: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling Foo              ( Bug.hs, interpreted )

Bug.hs:12:16: error:
    • Expected a type, but ‘eq’ has kind ‘k’
    • In the first argument of ‘Eq’, namely ‘eq’
      In the stand-alone deriving instance for
        ‘(Eq eq, Coercible Int eq) => Eq (IntAs eq)’
   |
12 |   instance (Eq eq, Coercible Int eq) => Eq (IntAs eq)
   |                ^^
```

Indeed, this is a duplicate of #29, so closing.

**Closed as completed by RyanGlScott** 2018-04-10 12:16 UTC
